import React from 'react';
import { RecommendedAction } from '../api/types';
import { Bot, FileText, Send, UserCheck, HelpCircle } from 'lucide-react';

interface ExplanationPanelProps {
  summary: string;
  dataSource?: 'llm' | 'template_fallback' | string;
  recommendedAction?: RecommendedAction | string;
}

export const ExplanationPanel: React.FC<ExplanationPanelProps> = ({
  summary,
  dataSource = 'template_fallback',
  recommendedAction = 'HUMAN_REVIEW_REQUIRED',
}) => {
  const isLLM = dataSource === 'llm';

  // Recommended Action styling
  let actionConfig = {
    bg: 'bg-amber-950/40 border-amber-500/50 text-amber-300',
    icon: UserCheck,
    label: 'HUMAN REVIEW REQUIRED (Multi-Model Disagreement / Forensic Triage)',
  };

  if (recommendedAction === 'SEND_DISCLOSURE_REQUEST') {
    actionConfig = {
      bg: 'bg-emerald-950/40 border-emerald-500/50 text-emerald-300',
      icon: Send,
      label: 'PROCEED: SEND FIU-IND / SECTION 91 CRPC DISCLOSURE REQUEST',
    };
  } else if (recommendedAction === 'INSUFFICIENT_SIGNAL') {
    actionConfig = {
      bg: 'bg-slate-800/60 border-slate-700 text-slate-400',
      icon: HelpCircle,
      label: 'INSUFFICIENT SIGNAL: EXPAND GRAPH DEPTH OR COLLECT MORE INTEL',
    };
  }

  const ActionIcon = actionConfig.icon;

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/90 p-5 shadow-lg">
      {/* Header Bar */}
      <div className="flex items-center justify-between pb-3 mb-4 border-b border-slate-800 flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-cyan-400" />
          <h2 className="text-sm font-semibold tracking-wide text-slate-200 uppercase font-mono">
            Investigator Plain-Language Brief
          </h2>
        </div>

        {/* Source Badge */}
        <div className="flex items-center gap-1.5">
          <span
            className={`inline-flex items-center gap-1 text-xs font-mono px-2.5 py-0.5 rounded-full border ${
              isLLM
                ? 'bg-purple-950/60 border-purple-500/50 text-purple-300'
                : 'bg-slate-800 border-slate-700 text-slate-400'
            }`}
          >
            <Bot className="w-3 h-3" />
            <span>Generated by: {isLLM ? 'Claude 3.5 Sonnet' : 'Forensic Template Engine'}</span>
          </span>
        </div>
      </div>

      {/* Recommended Action Alert Box */}
      <div className={`flex items-center gap-2.5 px-4 py-2.5 rounded-lg border text-xs font-mono mb-4 font-semibold ${actionConfig.bg}`}>
        <ActionIcon className="w-4 h-4 flex-shrink-0" />
        <span>RECOMMENDED ACTION: {actionConfig.label}</span>
      </div>

      {/* Main Narrative Prose */}
      <div className="prose prose-invert max-w-none text-slate-200 text-sm leading-relaxed space-y-2">
        {summary ? (
          <p className="font-normal font-sans text-base text-slate-100">{summary}</p>
        ) : (
          <p className="text-slate-500 italic">No attribution explanation available for this address.</p>
        )}
      </div>
    </div>
  );
};
